"""
dashboard/alert_system.py - Real-Time Alert Engine
=====================================================

Manages alerts generated by the MSPC system, stores them in a log,
and provides filtering/retrieval for the Streamlit dashboard.
"""

import os
import sys
from dataclasses import dataclass, field
from datetime import datetime
from typing import Dict, List, Optional

import numpy as np
import pandas as pd

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from config import config


@dataclass
class Alert:
    """Single MSPC alert record.

    Attributes:
        observation_id: Index of the flagged observation.
        timestamp: When the alert was raised.
        t2_value: Hotelling T² statistic.
        t2_ucl: T² upper control limit at time of alert.
        mewma_value: MEWMA T² statistic.
        mewma_ucl: MEWMA UCL at time of alert.
        alert_level: CRITICAL / HIGH / MEDIUM / LOW.
        true_label: Actual quality outcome (if known).
        top_contributors: Top 3 contributing components.
        recommendations: List of suggested actions.
    """

    observation_id: int
    timestamp: Optional[str] = None
    t2_value: float = 0.0
    t2_ucl: float = 0.0
    mewma_value: float = 0.0
    mewma_ucl: float = 0.0
    alert_level: str = "LOW"
    true_label: Optional[int] = None
    top_contributors: List[str] = field(default_factory=list)
    recommendations: List[str] = field(default_factory=list)


class AlertSystem:
    """Manage and query MSPC alerts.

    Args:
        cfg: Optional configuration override.
    """

    def __init__(self, cfg=None):
        self.cfg = cfg or config
        self.alerts: List[Alert] = []

    def generate_alerts(self, results_df: pd.DataFrame) -> List[Alert]:
        """Create alerts from combined MSPC results.

        Args:
            results_df: DataFrame from :class:`CombinedMSPCSystem.monitor`.

        Returns:
            List of :class:`Alert` instances for signalled observations.
        """
        self.alerts = []

        for _, row in results_df.iterrows():
            if not row.get("combined_signal", False):
                continue

            t2_val = float(row.get("t2_value", 0))
            ucl = float(row.get("t2_ucl", 1))
            exceedance = (t2_val - ucl) / max(ucl, 1e-6) * 100
            if exceedance > 200:
                level = "CRITICAL"
            elif exceedance > 100:
                level = "HIGH"
            elif exceedance > 50:
                level = "MEDIUM"
            else:
                level = "LOW"

            alert = Alert(
                observation_id=int(row.get("observation_id", 0)),
                t2_value=t2_val,
                t2_ucl=ucl,
                mewma_value=float(row.get("mewma_value", 0)),
                mewma_ucl=float(row.get("mewma_ucl", 0)),
                alert_level=level,
                true_label=int(row["true_label"]) if "true_label" in row and pd.notna(row["true_label"]) else None,
                recommendations=[
                    "Inspect process parameters",
                    "Check sensor calibration",
                    "Review maintenance log",
                ],
            )
            self.alerts.append(alert)

        return self.alerts

    def get_alert_df(self) -> pd.DataFrame:
        """Return alerts as a DataFrame.

        Returns:
            DataFrame with one row per alert.
        """
        if not self.alerts:
            return pd.DataFrame()
        records = []
        for a in self.alerts:
            records.append({
                "observation_id": a.observation_id,
                "t2_value": round(a.t2_value, 2),
                "t2_ucl": round(a.t2_ucl, 2),
                "mewma_value": round(a.mewma_value, 2),
                "alert_level": a.alert_level,
                "true_label": a.true_label,
                "top_contributors": a.top_contributors,
                "recommendations": a.recommendations,
            })
        return pd.DataFrame(records)

    def get_summary(self) -> Dict:
        """Return alert summary statistics.

        Returns:
            Dictionary with counts per level and TP/FP breakdown.
        """
        levels = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0}
        tp, fp = 0, 0
        for a in self.alerts:
            levels[a.alert_level] = levels.get(a.alert_level, 0) + 1
            if a.true_label == 1:
                tp += 1
            elif a.true_label == 0:
                fp += 1
        return {"levels": levels, "TP": tp, "FP": fp, "total": len(self.alerts)}
