"""
visualization/pca_plots.py - PCA Visualisation Suite
=======================================================

Stand-alone plotting helpers for PCA results (scree, biplot, loadings).
These supplement the plots already generated by the PCA engine itself.
"""

import os
import sys
from typing import List, Optional

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from config import config


class PCAPlotter:
    """Additional PCA-related plots.

    Args:
        cfg: Optional configuration override.
    """

    def __init__(self, cfg=None):
        self.cfg = cfg or config
        self.fig_dir = os.path.join(self.cfg.figures_dir, "pca")
        os.makedirs(self.fig_dir, exist_ok=True)

    def plot_variance_retention_bar(
        self,
        n_components_list: List[int],
        variance_list: List[float],
        filename: str = "variance_retention_bar.png",
    ) -> None:
        """Bar chart of variance retention for different component counts.

        Args:
            n_components_list: List of component counts.
            variance_list: Corresponding cumulative variance fractions.
            filename: Output filename.
        """
        fig, ax = plt.subplots(figsize=(10, 6))
        colours = ["#4C72B0" if v < 0.95 else "#55A868" for v in variance_list]
        ax.bar(
            [str(n) for n in n_components_list],
            [v * 100 for v in variance_list],
            color=colours,
            edgecolor="black",
        )
        ax.axhline(95, ls="--", color="red", lw=1, label="95 %")
        ax.set_xlabel("Number of Components")
        ax.set_ylabel("Cumulative Variance (%)")
        ax.set_title("Variance Retention by Component Count", fontweight="bold")
        ax.legend()
        plt.tight_layout()

        path = os.path.join(self.fig_dir, filename)
        fig.savefig(path, dpi=self.cfg.figure_dpi)
        plt.close(fig)
        print(f"  ✓ Saved → {path}")

    def plot_t2_spe_scatter(
        self,
        t2_values: np.ndarray,
        spe_values: np.ndarray,
        y: Optional[np.ndarray] = None,
        t2_ucl: float = 0.0,
        spe_ucl: float = 0.0,
        filename: str = "t2_spe_scatter.png",
    ) -> None:
        """T² vs SPE scatter coloured by class.

        Args:
            t2_values: Hotelling T² from PCA.
            spe_values: SPE / Q statistic.
            y: Optional labels.
            t2_ucl: T² control limit.
            spe_ucl: SPE control limit.
            filename: Output filename.
        """
        fig, ax = plt.subplots(figsize=(10, 8))

        if y is not None:
            y = np.asarray(y)
            ax.scatter(t2_values[y == 0], spe_values[y == 0],
                       c="steelblue", alpha=0.4, s=15, label="Pass")
            ax.scatter(t2_values[y == 1], spe_values[y == 1],
                       c="crimson", alpha=0.7, s=40, marker="*", label="Fail")
        else:
            ax.scatter(t2_values, spe_values, c="steelblue", alpha=0.4, s=15)

        if t2_ucl > 0:
            ax.axvline(t2_ucl, ls="--", color="red", lw=1, label=f"T² UCL={t2_ucl:.1f}")
        if spe_ucl > 0:
            ax.axhline(spe_ucl, ls="--", color="orange", lw=1, label=f"SPE UCL={spe_ucl:.1f}")

        ax.set_xlabel("Hotelling T²", fontsize=12)
        ax.set_ylabel("SPE (Q statistic)", fontsize=12)
        ax.set_title("T² vs SPE Diagnostic Plot", fontweight="bold", fontsize=14)
        ax.legend()
        plt.tight_layout()

        path = os.path.join(self.fig_dir, filename)
        fig.savefig(path, dpi=self.cfg.figure_dpi)
        plt.close(fig)
        print(f"  ✓ Saved → {path}")
